import React from "react";
import Skill from "./Skill";

export default function Skills() {
  return (
    <div className="flex items-center justify-center w-full p-8 bg-green-light">
      <div className="flex flex-wrap items-center justify-center max-w-3xl gap-4">
        <Skill
          link={"https://react.dev/"}
          text={"ReactJS"}
          imageSrc={"images/skills/react.png"}
        ></Skill>
        <Skill
          text={"React Query"}
          link={"https://tanstack.com/query/v3/"}
          imageSrc={"images/skills/react-query.png"}
        ></Skill>
        <Skill
          link={"https://redux.js.org/"}
          text={"Redux"}
          imageSrc={"images/skills/redux.png"}
        ></Skill>

        <Skill
          link={"https://nextjs.org/"}
          text={"NextJS"}
          imageSrc={"images/skills/nextjs.png"}
        ></Skill>
        <Skill
          link={"https://next-auth.js.org/"}
          text={"NextAuth"}
          imageSrc={"images/skills/next-auth.png"}
        ></Skill>
        <Skill
          link={"https://www.typescriptlang.org/"}
          text={"TypeScript"}
          imageSrc={"images/skills/typescript.png"}
        ></Skill>
        <Skill
          link={"https://jestjs.io//"}
          text={"Jest"}
          imageSrc={"images/skills/jest.png"}
        ></Skill>
        <Skill
          link={"https://www.prisma.io/"}
          text={"Prisma"}
          imageSrc={"images/skills/prisma.png"}
        ></Skill>
        <Skill
          link={"https://www.postgresql.org/"}
          text={"postgreSQL"}
          imageSrc={"images/skills/postgresql.png"}
        ></Skill>
        <Skill
          link={"https://www.mysql.com/"}
          text={"MySql"}
          imageSrc={"images/skills/mysql.png"}
        ></Skill>

        <Skill
          link={"https://firebase.google.com/"}
          text={"Firebase"}
          imageSrc={"images/skills/firebase.png"}
        ></Skill>
        <Skill
          link={"https://tailwindcss.com/"}
          text={"TailwindCSS"}
          imageSrc={"images/skills/tailwind.png"}
        ></Skill>
        <Skill
          link={"https://material-ui.com/"}
          text={"MaterialUI"}
          imageSrc={"images/skills/mui.png"}
        ></Skill>
        <Skill
          link={"https://chakra-ui.com/"}
          text={"ChakraUI"}
          imageSrc={"images/skills/chakraui.png"}
        ></Skill>
        <Skill
          link={"https://www.vercel.com/"}
          text={"Vercel"}
          imageSrc={"images/skills/vercel.svg"}
        ></Skill>
        <Skill
          link={"https://www.heroku.com/"}
          text={"Heroku"}
          imageSrc={"images/skills/heroku.png"}
        ></Skill>
        <Skill
          link={"https://cloud.google.com/"}
          text={"GCP"}
          imageSrc={"images/skills/gcp-logo.webp"}
        ></Skill>
        <Skill
          link={"https://www.w3schools.com/html/"}
          text={"HTML"}
          imageSrc={"images/skills/html-5.png"}
        ></Skill>
        <Skill
          link={"https://www.w3schools.com/css/"}
          text={"CSS"}
          imageSrc={"images/skills/css-3.png"}
        ></Skill>
        <Skill
          link={"https://www.javascript.com/"}
          text={"JavaScript"}
          imageSrc={"images/skills/js.png"}
        ></Skill>

        <Skill
          link={"https://www.php.net/"}
          text={"PHP"}
          imageSrc={"images/skills/php.png"}
        ></Skill>

        <Skill
          link={"https://nodejs.org/en"}
          text={"NodeJS"}
          imageSrc={"images/skills/node-js.png"}
        ></Skill>
        <Skill
          link={"https://expressjs.com/"}
          text={"Express"}
          imageSrc={"images/skills/express.png"}
        ></Skill>

        <Skill
          link={"https://www.python.org/"}
          text={"Python"}
          imageSrc={"images/skills/python.png"}
        ></Skill>
        <Skill
          link={"https://www.java.com/en/"}
          text={"Java"}
          imageSrc={"images/skills/java.webp"}
        ></Skill>
        <Skill
          link={"https://android.com/"}
          text={"Android"}
          imageSrc={"images/skills/android.png"}
        ></Skill>
        <Skill
          link={"https://flutter.dev/"}
          text={"Flutter"}
          imageSrc={"images/skills/flutter.png"}
        ></Skill>
        <Skill
          link={"https://visualstudio.microsoft.com/"}
          text={"VS Code"}
          imageSrc={"images/skills/vscode.png"}
        ></Skill>
        <Skill
          link={"https://visualstudio.microsoft.com/"}
          text={"Visual Studio"}
          imageSrc={"images/skills/visualstudio.png"}
        ></Skill>
        <Skill
          link={"https://dotnet.microsoft.com/en-us/languages/csharp"}
          text={"C#"}
          imageSrc={"images/skills/c-sharp.png"}
        ></Skill>
        <Skill
          link={"https://unity.com/"}
          text={"Unity"}
          imageSrc={"images/skills/unity.png"}
        ></Skill>

        <Skill
          link={"https://www.github.com/"}
          text={"Github"}
          imageSrc={"images/skills/github.png"}
        ></Skill>
        <Skill
          link={"https://git-scm.com/"}
          text={"Git"}
          imageSrc={"images/skills/git.png"}
        ></Skill>
        <Skill
          link={"https://www.figma.com/"}
          text={"Figma"}
          imageSrc={"images/skills/figma.png"}
        ></Skill>
        <Skill
          link={"https://www.atlassian.com/software/jira"}
          text={"Jira"}
          imageSrc={"images/skills/jira.webp"}
        ></Skill>
      </div>
    </div>
  );
}
